version: "3"

services:
  web:
    container_name: web_x
    build:
      context: ./src
    ports:
      - 8080:80
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    container_name: db_x
    build:
      context: ./src/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - /docker-entrypoint-initdb.d/
